# Generated by Django 5.1 on 2024-08-17 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='pais_origen_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='familiares.pais'),
        ),
    ]
